<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Block Farm Editor USync</Title>
      <VersionPrefix>17.1.0</VersionPrefix>
      <PackageOutputPath>..\</PackageOutputPath>
      <Description>Package allowing full USync integration for BlockFarmEditor</Description>
      <PackageReadmeFile>README.md</PackageReadmeFile>
      <PackageReleaseNotes>Inital Release</PackageReleaseNotes>
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uSync" Version="17.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlockFarmEditor\BlockFarmEditor.Umbraco.Core\BlockFarmEditor.Umbraco.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
